[package]
name = "walter-db"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
rusqlite = "0.32.1"
rustyline = "15.0.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
